server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb+srv://cbhanukawp2002_db_user:SBLABJGXoRp6OIMA@shiftsync-notification.9pknogf.mongodb.net/shiftsync_notifications?retryWrites=true&w=majority&appName=shiftsync-notification